# Generated by Django 3.2.4 on 2022-11-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haruapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
